server:
  port: 5000

spring:
  profiles:
    active: develop
  servlet:
    multipart:
      enabled: true
  jmx:
    enabled: true
  pid:
    file: logs/kuku-api.pid


klaytn:
#  endpoint: https://kaikas.baobab.klaytn.net:8651
#  chain: TEST
  chain: MAIN
  endpoint: https://kaikas.cypress.klaytn.net:8651/

ethereum:
  endpoint: http://localhost:8545
  chain: MAIN

ipfs:
  host:
  port:
